---
extends: default

rules:
  line-length: disable
  new-lines:
    type: unix
  new-line-at-end-of-file:
    level: warning
  trailing-spaces:
    level: warning
  comments:
    min-spaces-from-content: 1
